/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/announce": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * BitTorrent announce
     * @description The tracker announce endpoint, spoken by BitTorrent clients rather than by browsers. It is not a JSON API: the response is a bencoded dictionary served as text/plain, and every failure — including an invalid passkey — is reported as HTTP 200 with a bencoded `{"failure reason": "..."}` body, because that is what clients understand.
     *
     *     Authentication is the member's 32-character hex passkey, carried in the query string. The passkey is baked into the announce URL of every .torrent file downloaded from the site, so clients send it without the user ever seeing it.
     */
    get: operations["trackerAnnounce"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scrape": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * BitTorrent scrape
     * @description Swarm counts for one or more torrents, bencoded. Repeat `info_hash` to scrape several at once; hashes that are not 20 bytes after decoding are ignored rather than rejected.
     *
     *     Unlike /announce this takes no passkey — it reports only aggregate seeder, leecher and completion counts, which say nothing about who is in the swarm.
     */
    get: operations["trackerScrape"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get site-wide statistics */
    get: operations["getStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all torrent categories */
    get: operations["getCategories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: operations["authRegister"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login with username and password */
    post: operations["authLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh access token using refresh token */
    post: operations["authRefresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout and invalidate current session */
    post: operations["authLogout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password reset link
     * @description Sends a password reset link to the given email if it exists. Always returns 200 to prevent email enumeration.
     */
    post: operations["authForgotPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset password using a reset token
     * @description Validates the reset token, sets the new password, and invalidates all active sessions for the user.
     */
    post: operations["authResetPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current authenticated user's full profile
     * @description Returns the full owner profile for the authenticated user, including private fields like email, masked passkey, invites, and warned status.
     */
    get: operations["authMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a user's profile
     * @description Returns a user's public profile, looked up by username. If the authenticated user is viewing their own profile, private fields (email, passkey, invites, warned, last_login) are also included.
     */
    get: operations["getUserProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update the current user's profile */
    put: operations["updateProfile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Change the current user's password
     * @description Verifies the current password, sets a new one, and invalidates all other sessions (keeps the current session active).
     */
    put: operations["changePassword"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me/passkey": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Regenerate the current user's passkey
     * @description Generates a new 32-character hex passkey. The old passkey is immediately invalidated.
     */
    post: operations["regeneratePasskey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}/announce-log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a member's announce log and monthly transfer totals
     * @description Returns the raw announces the tracker recorded for this member, newest first, together with their per-month transfer totals.
     *     The raw rows are pruned once they pass the site's `announce_log_retention_days` window, so the listing only reaches as far back as `retention_days` (0 means pruning is disabled and rows are kept indefinitely). The monthly totals are aggregated before the prune runs and are kept permanently, so they still cover months whose raw rows are gone.
     *     Readable by the member themselves and by staff only: the log contains IP addresses and peer IDs.
     */
    get: operations["getUserAnnounceLog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}/announce-log/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download a member's announce log as CSV
     * @description Streams every retained announce for this member as CSV, oldest first, with one header row. Columns: `announced_at`, `torrent_id`, `torrent_name`, `event`, `ip`, `port`, `peer_id` (hex), `uploaded`, `downloaded`, `left_bytes`, `uploaded_delta`, `downloaded_delta`, `counted_downloaded_delta`, `seeder`.
     *     This is the member's own copy of the personal data the tracker holds about their client. Same audience as the listing: the member, or staff.
     *     The response is streamed, so a failure part-way through arrives as a truncated body rather than an error status — the row count is the check.
     */
    get: operations["exportUserAnnounceLog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/torrents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browse and search torrents */
    get: operations["listTorrents"];
    put?: never;
    /** Upload a new torrent */
    post: operations["uploadTorrent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/torrents/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get torrent details */
    get: operations["getTorrent"];
    /**
     * Edit torrent metadata
     * @description Update torrent fields. Only the torrent owner or an admin (group_id=1) may edit.
     *     Staff-only fields (banned, free) are rejected for non-admin users.
     */
    put: operations["editTorrent"];
    post?: never;
    /**
     * Delete a torrent
     * @description Delete a torrent and its stored .torrent file.
     *     Only the torrent owner or an admin (group_id=1) may delete.
     *     A reason is required.
     */
    delete: operations["deleteTorrent"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/torrents/{id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download .torrent file with personalized announce URL
     * @description Returns the .torrent file with the caller's own passkey substituted into its announce URL.
     *
     *     Authentication is by bearer token and the caller needs the `download` capability. A `passkey` query parameter is NOT accepted here — see the note on GET /api/v1/rss, whose enclosure URLs are built as though it were.
     */
    get: operations["downloadTorrent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * RSS feed of the newest torrents
     * @description An RSS 2.0 feed of the most recently uploaded torrents, authenticated by passkey rather than by bearer token so that feed readers and automation can subscribe to a plain URL.
     *
     *     KNOWN LIMITATION — the `<enclosure url="...">` of each item points at `/api/v1/torrents/{id}/download?passkey=...`, but that endpoint does not accept a passkey: it requires a bearer token and the `download` capability. Following an enclosure URL therefore returns 401 unless the client is already carrying a session. Use the enclosure only to identify the torrent, and fetch the .torrent file with an authenticated request.
     */
    get: operations["getRSSFeed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/announce-stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Live announcement stream (default feed)
     * @description Server-sent events carrying new-torrent announcements as they happen, for the default feed. Equivalent to GET /api/v1/announce-stream/{slug} with the default slug; it predates multiple feeds and is kept so an already-open page reconnects rather than failing forever.
     */
    get: operations["announceStreamDefault"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/announce-stream/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Live announcement stream
     * @description Server-sent events carrying new-torrent announcements for one feed, as they happen. Each frame is an `announcement` event whose data is the rendered announcement; comment lines are sent periodically as heartbeats.
     *
     *     Authentication is a `token` query parameter holding an access token, because EventSource cannot set an Authorization header. Access additionally requires the `can_feed` privilege, checked live on every connect, so a revoked privilege bites at the next reconnect. A member may hold a limited number of concurrent streams across all feeds; past that the connection is refused with 429.
     *
     *     An unrecognised but well-formed slug opens a stream that simply stays quiet — feeds are admin-configurable and the hub does not race their edits.
     */
    get: operations["announceStream"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/torrents/{id}/moderation/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve a torrent awaiting moderation
     * @description Approves a torrent in the moderation queue. Authorization happens in the service layer: staff may approve any pending torrent, and an uploader holding the self-approve privilege may approve their own.
     */
    post: operations["approveTorrent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/torrents/{id}/moderation/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read the moderation thread for a torrent
     * @description The discussion between the moderators and the uploader about a submitted torrent. Readable by staff and by the torrent's own uploader — the uploader needs to see why their upload was held.
     */
    get: operations["listModerationMessages"];
    put?: never;
    /**
     * Post to the moderation thread for a torrent
     * @description Adds a message to the moderation discussion. Writable by staff and by the torrent's own uploader.
     */
    post: operations["postModerationMessage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a report
     * @description Submit a report about a torrent. One report per user per torrent is enforced.
     *     Requires authentication.
     */
    post: operations["createReport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List reports (admin only)
     * @description Returns a paginated list of reports. Only accessible by administrators (group_id=1).
     */
    get: operations["listReports"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/reports/{id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Resolve a report (admin only)
     * @description Marks a report as resolved. Only accessible by administrators (group_id=1).
     */
    put: operations["resolveReport"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/torrents/{id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List comments for a torrent */
    get: operations["listComments"];
    put?: never;
    /** Add a comment to a torrent */
    post: operations["createComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Edit a comment
     * @description Only the comment author or an admin (group_id=1) may edit.
     */
    put: operations["editComment"];
    post?: never;
    /**
     * Delete a comment
     * @description Only admins (group_id=1) may delete comments.
     */
    delete: operations["deleteComment"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/torrents/{id}/rating": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get rating statistics for a torrent
     * @description Returns average rating, total count, and the authenticated user's rating if any.
     */
    get: operations["getRatingStats"];
    put?: never;
    /**
     * Rate a torrent (1-5 scale, upsert)
     * @description One vote per user per torrent. Re-submitting updates the existing rating.
     */
    post: operations["rateTorrent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterRequest: {
      /** @example johndoe */
      username: string;
      /**
       * Format: email
       * @example john@example.com
       */
      email: string;
      /** @example mysecurepassword */
      password: string;
    };
    LoginRequest: {
      /** @example johndoe */
      username: string;
      /** @example mysecurepassword */
      password: string;
    };
    RefreshRequest: {
      /** @example abc123def456... */
      refresh_token: string;
    };
    AuthTokens: {
      /** @description 64-character hex token, expires in 1 hour */
      access_token?: string;
      /** @description 64-character hex token, expires in 30 days */
      refresh_token?: string;
      /**
       * @description Seconds until access token expires
       * @example 3600
       */
      expires_in?: number;
    };
    AuthResponse: {
      user?: components["schemas"]["UserProfile"];
      tokens?: components["schemas"]["AuthTokens"];
      /** @description Present and true on registration when the site requires email confirmation before the account can be used. Omitted otherwise, so treat absence as false. */
      email_confirmation_required?: boolean;
    };
    /** @description Profile visible to any authenticated user */
    PublicProfile: {
      /** Format: int64 */
      id?: number;
      username?: string;
      /** Format: int64 */
      group_id?: number;
      avatar?: string | null;
      title?: string | null;
      /** @description User bio */
      info?: string | null;
      /** Format: int64 */
      uploaded?: number;
      /** Format: int64 */
      downloaded?: number;
      /**
       * Format: double
       * @description uploaded / downloaded (Infinity if downloaded=0 and uploaded>0, 0 if both zero)
       */
      ratio?: number;
      donor?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    /** @description Extended profile visible only to the profile owner */
    OwnerProfile: components["schemas"]["PublicProfile"] & {
      /** Format: email */
      email?: string;
      /**
       * @description Masked passkey (first 4 + last 4 chars visible)
       * @example a1b2************************c5d6
       */
      passkey?: string;
      invites?: number;
      warned?: boolean;
      /** Format: date-time */
      last_login?: string | null;
    };
    /** @description Deprecated - use PublicProfile or OwnerProfile instead */
    UserProfile: {
      /** Format: int64 */
      id?: number;
      username?: string;
      /** Format: email */
      email?: string;
      /** Format: int64 */
      group_id?: number;
      /** Format: int64 */
      uploaded?: number;
      /** Format: int64 */
      downloaded?: number;
      enabled?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    UpdateProfileRequest: {
      /**
       * Format: uri
       * @description Avatar URL (must be http or https)
       * @example https://example.com/avatar.png
       */
      avatar?: string;
      /** @description Custom title */
      title?: string;
      /** @description User bio */
      info?: string;
    };
    ChangePasswordRequest: {
      /** @description The current password for verification */
      current_password: string;
      /** @description The new password */
      new_password: string;
    };
    /** @description One announce, exactly as the client reported it. Retained only for `announce_log_retention_days`. */
    AnnounceLogEntry: {
      /** Format: int64 */
      id?: number;
      /**
       * Format: int64
       * @description Null once the torrent has been deleted — the log outlives it
       */
      torrent_id?: number | null;
      /** @description "Deleted Torrent" when the torrent is gone */
      torrent_name?: string;
      /**
       * @description "announce" for a periodic update carrying no event
       * @enum {string}
       */
      event?: "started" | "stopped" | "completed" | "announce";
      ip?: string;
      port?: number;
      /**
       * @description Hex-encoded — the raw value is arbitrary bytes
       * @example 2d7142343535302d
       */
      peer_id?: string;
      /**
       * Format: int64
       * @description Client-reported cumulative total for the session
       */
      uploaded?: number;
      /**
       * Format: int64
       * @description Client-reported cumulative total for the session
       */
      downloaded?: number;
      /** Format: int64 */
      left_bytes?: number;
      /**
       * Format: int64
       * @description Bytes uploaded since this peer's previous announce
       */
      uploaded_delta?: number;
      /**
       * Format: int64
       * @description Raw, before any freeleech discount
       */
      downloaded_delta?: number;
      /**
       * Format: int64
       * @description After freeleech discount — what counted toward ratio
       */
      counted_downloaded_delta?: number;
      seeder?: boolean;
      /** Format: date-time */
      announced_at?: string;
    };
    /** @description One calendar month (UTC) of totals, aggregated from the raw log before it was pruned and kept permanently. */
    AnnounceLogPeriod: {
      /** @example 2026-07 */
      year_month?: string;
      /**
       * Format: int64
       * @description Sum of per-announce upload deltas for the month
       */
      uploaded?: number;
      /**
       * Format: int64
       * @description Raw download total, before freeleech discounts
       */
      downloaded?: number;
      /**
       * Format: int64
       * @description What counted toward ratio for the month
       */
      counted_downloaded?: number;
      /** Format: int64 */
      announces?: number;
      /**
       * Format: int64
       * @description How many of those announces were made while seeding
       */
      seed_announces?: number;
      /**
       * Format: double
       * @description uploaded / counted_downloaded. 0 when the month is empty, -1 when nothing counted against the member (an effectively infinite ratio).
       */
      ratio?: number;
    };
    AnnounceLogResponse: {
      events?: components["schemas"]["AnnounceLogEntry"][];
      /**
       * Format: int64
       * @description Total retained announces for this member
       */
      total?: number;
      page?: number;
      per_page?: number;
      /** @description Monthly totals, newest month first, up to 120 months */
      monthly?: components["schemas"]["AnnounceLogPeriod"][];
      /** @description How many days of raw announces the site keeps. 0 means pruning is disabled and nothing is deleted. */
      retention_days?: number;
    };
    Torrent: {
      /** Format: int64 */
      id?: number;
      name?: string;
      /**
       * @description Hex-encoded SHA1 info hash
       * @example a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0
       */
      info_hash?: string;
      /**
       * Format: int64
       * @description Total size in bytes
       */
      size?: number;
      description?: string;
      /** Format: int64 */
      category_id?: number;
      /** @description Name of the category (resolved via JOIN) */
      category_name?: string;
      /** @description Icon for the category, resolved via the same JOIN. May be empty. */
      category_image_url?: string;
      /** Format: int64 */
      uploader_id?: number;
      anonymous?: boolean;
      /** @description Display name of the uploader ("Anonymous" when anonymous=true) */
      uploader_name?: string;
      /** @description Whether the uploader has an active warning (false when anonymous=true) */
      uploader_warned?: boolean;
      seeders?: number;
      leechers?: number;
      times_completed?: number;
      comments_count?: number;
      file_count?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    Category: {
      /** Format: int64 */
      id?: number;
      name?: string;
      /** Format: int64 */
      parent_id?: number | null;
      sort_order?: number;
    };
    SiteStats: {
      /**
       * Format: int64
       * @description Number of enabled users
       */
      users?: number;
      /**
       * Format: int64
       * @description Number of visible, non-banned torrents
       */
      torrents?: number;
      /**
       * Format: int64
       * @description Number of active peers
       */
      peers?: number;
    };
    ForgotPasswordRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
    };
    ResetPasswordRequest: {
      /**
       * @description The raw reset token from the email link
       * @example abc123def456...
       */
      token: string;
      /**
       * @description The new password
       * @example mynewsecurepassword
       */
      password: string;
    };
    MessageResponse: {
      /** @example Operation completed successfully */
      message?: string;
    };
    EditTorrentRequest: {
      /** @description New torrent name (must not be empty if provided) */
      name?: string;
      /** @description New torrent description */
      description?: string;
      /**
       * Format: int64
       * @description New category ID
       */
      category_id?: number;
      /** @description Whether the upload is anonymous */
      anonymous?: boolean;
      /** @description Staff-only — ban/unban the torrent */
      banned?: boolean;
      /** @description Staff-only — enable/disable freeleech */
      free?: boolean;
    };
    DeleteTorrentRequest: {
      /** @description Reason for deleting the torrent */
      reason: string;
    };
    CreateReportRequest: {
      /**
       * Format: int64
       * @description ID of the torrent being reported (optional for general reports)
       */
      torrent_id?: number;
      /** @description Reason for the report */
      reason: string;
    };
    Report: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      reporter_id?: number;
      /** Format: int64 */
      torrent_id?: number | null;
      reason?: string;
      resolved?: boolean;
      /** Format: int64 */
      resolved_by?: number | null;
      /** Format: date-time */
      resolved_at?: string | null;
      /** Format: date-time */
      created_at?: string;
    };
    CreateCommentRequest: {
      /**
       * @description Comment text
       * @example Great torrent, thanks!
       */
      body: string;
    };
    Comment: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      torrent_id?: number;
      /** Format: int64 */
      user_id?: number;
      username?: string;
      body?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    RateRequest: {
      /**
       * @description Rating from 1 to 5
       * @example 4
       */
      rating: number;
    };
    RatingStats: {
      /**
       * Format: double
       * @description Average rating (0 if no ratings)
       */
      average?: number;
      /** @description Total number of ratings */
      count?: number;
      /** @description The authenticated user's rating (omitted if not rated) */
      user_rating?: number;
    };
    ModerationMessageRequest: {
      /** @description The message to add to the moderation thread */
      body: string;
    };
    ModerationMessage: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      torrent_id?: number;
      /** Format: int64 */
      author_id?: number;
      author_username?: string;
      body?: string;
      /** Format: date-time */
      created_at?: string;
    };
    ErrorResponse: {
      error?: {
        code?: string;
        message?: string;
      };
    };
  };
  responses: {
    /** @description An open server-sent event stream */
    AnnounceStream: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example retry: 5000
         *
         *     event: announcement
         *     id: 42
         *     data: {"name":"Some.Torrent","url":"https://example.org/torrent/1"}
         */
        "text/event-stream": string;
      };
    };
    /** @description Missing, invalid or expired token */
    StreamUnauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The caller does not hold the can_feed privilege */
    StreamForbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The caller already holds the maximum number of concurrent streams */
    StreamTooMany: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description An access token, passed in the query string because EventSource cannot set an Authorization header. */
    StreamToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example ok */
            status?: string;
          };
        };
      };
    };
  };
  trackerAnnounce: {
    parameters: {
      query: {
        /** @description The member's 32-character hex passkey */
        passkey: string;
        /** @description The torrent's SHA1 info hash. Accepted either as the raw 20-byte binary value percent-encoded (what BitTorrent clients send) or as 40 hex characters. */
        info_hash: string;
        /** @description The client's 20-byte peer id, percent-encoded */
        peer_id: string;
        /** @description The port the client is listening on */
        port: number;
        /** @description Bytes uploaded this session */
        uploaded?: number;
        /** @description Bytes downloaded this session */
        downloaded?: number;
        /** @description Bytes left to download */
        left?: number;
        /** @description The announce event. Omitted (or empty) for a periodic announce. */
        event?: "" | "started" | "stopped" | "completed";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A bencoded announce response, or a bencoded failure dictionary. Errors do not use HTTP status codes. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  trackerScrape: {
    parameters: {
      query: {
        /** @description One or more raw 20-byte SHA1 info hashes, percent-encoded. Repeat the parameter to scrape multiple torrents. */
        info_hash: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A bencoded `{"files": {...}}` dictionary, or a bencoded failure dictionary when no usable info_hash was supplied. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  getStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Site statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            stats?: components["schemas"]["SiteStats"];
          };
        };
      };
      /** @description Missing or invalid authorization header */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of categories */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            categories?: components["schemas"]["Category"][];
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authRegister: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description User created and auto-logged in */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Username or email already taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authRefresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Tokens refreshed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            tokens?: components["schemas"]["AuthTokens"];
          };
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid or expired refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authLogout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session invalidated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid authorization header */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authForgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Generic success response (does not reveal if email exists) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authResetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Password reset successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Invalid or expired reset token */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation error (password too short/long) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user's full profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user?: components["schemas"]["OwnerProfile"];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getUserProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The member's username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile (public or owner view) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user?:
              | components["schemas"]["PublicProfile"]
              | components["schemas"]["OwnerProfile"];
          };
        };
      };
      /** @description Missing username */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      /** @description Updated user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user?: components["schemas"]["OwnerProfile"];
          };
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Password changed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Current password incorrect or not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation error (new password too short/long) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  regeneratePasskey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description New passkey generated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /**
             * @description The new 32-character hex passkey
             * @example a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6
             */
            passkey?: string;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getUserAnnounceLog: {
    parameters: {
      query?: {
        page?: number;
        per_page?: number;
      };
      header?: never;
      path: {
        /** @description The member's numeric ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Announce log page and monthly totals */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnnounceLogResponse"];
        };
      };
      /** @description Invalid user ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not the member and not staff */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  exportUserAnnounceLog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The member's numeric ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CSV export */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": string;
        };
      };
      /** @description Invalid user ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not the member and not staff */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listTorrents: {
    parameters: {
      query?: {
        /** @description Search term for torrent name. Minimum 2 characters. Queries with 3+ characters use PostgreSQL full-text search (tsvector/GIN) with relevance ranking. Queries with exactly 2 characters fall back to case-insensitive substring matching (ILIKE). When full-text search is active and no explicit sort field is specified, results are ordered by relevance. */
        search?: string;
        /** @description Filter by category ID */
        cat?: number;
        /** @description Sort field */
        sort?: "name" | "created_at" | "size" | "seeders" | "leechers";
        /** @description Sort order */
        order?: "asc" | "desc";
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        per_page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of torrents */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            torrents?: components["schemas"]["Torrent"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            per_page?: number;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  uploadTorrent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description The .torrent file to upload
           */
          torrent_file: string;
          /**
           * Format: int64
           * @description Category ID for the torrent
           */
          category_id: number;
          /** @description Display name (defaults to name from .torrent file) */
          name?: string;
          /** @description Torrent description */
          description?: string;
          /**
           * @description Whether to hide the uploader's identity
           * @default false
           */
          anonymous?: boolean;
        };
      };
    };
    responses: {
      /** @description Torrent uploaded successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            torrent?: components["schemas"]["Torrent"];
          };
        };
      };
      /** @description Invalid torrent file or missing fields */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Duplicate torrent (info_hash already exists) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getTorrent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Torrent details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            torrent?: components["schemas"]["Torrent"];
          };
        };
      };
      /** @description Invalid torrent ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  editTorrent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditTorrentRequest"];
      };
    };
    responses: {
      /** @description Updated torrent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            torrent?: components["schemas"]["Torrent"];
          };
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — not owner or admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteTorrent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteTorrentRequest"];
      };
    };
    responses: {
      /** @description Torrent deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid request or missing reason */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — not owner or admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  downloadTorrent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The .torrent file */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/x-bittorrent": string;
        };
      };
      /** @description Invalid torrent ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — the download capability is not held */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getRSSFeed: {
    parameters: {
      query: {
        /** @description The member's 32-character hex passkey */
        passkey: string;
        /** @description How many torrents to include. Values above 100 are clamped to 100; values that are not a positive integer fall back to the default. */
        limit?: number;
        /** @description Restrict the feed to a single category ID */
        cat?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description RSS 2.0 feed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/rss+xml": string;
        };
      };
      /** @description Missing or invalid passkey */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  announceStreamDefault: {
    parameters: {
      query: {
        /** @description An access token, passed in the query string because EventSource cannot set an Authorization header. */
        token: components["parameters"]["StreamToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["AnnounceStream"];
      401: components["responses"]["StreamUnauthorized"];
      403: components["responses"]["StreamForbidden"];
      429: components["responses"]["StreamTooMany"];
    };
  };
  announceStream: {
    parameters: {
      query: {
        /** @description An access token, passed in the query string because EventSource cannot set an Authorization header. */
        token: components["parameters"]["StreamToken"];
      };
      header?: never;
      path: {
        /** @description The feed's slug, as listed by GET /api/v1/announce-feeds */
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["AnnounceStream"];
      401: components["responses"]["StreamUnauthorized"];
      403: components["responses"]["StreamForbidden"];
      /** @description Malformed feed slug */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      429: components["responses"]["StreamTooMany"];
    };
  };
  approveTorrent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The approved torrent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            torrent?: components["schemas"]["Torrent"];
          };
        };
      };
      /** @description Invalid torrent ID or the torrent is not awaiting approval */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — neither staff nor a self-approving uploader */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listModerationMessages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The moderation thread, oldest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            messages?: components["schemas"]["ModerationMessage"][];
          };
        };
      };
      /** @description Invalid torrent ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — neither staff nor the uploader */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  postModerationMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModerationMessageRequest"];
      };
    };
    responses: {
      /** @description Message posted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            message?: components["schemas"]["ModerationMessage"];
          };
        };
      };
      /** @description Invalid request body or empty body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — neither staff nor the uploader */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createReport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateReportRequest"];
      };
    };
    responses: {
      /** @description Report submitted successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            report?: components["schemas"]["Report"];
          };
        };
      };
      /** @description Invalid request (missing reason) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Duplicate report (already reported this item) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listReports: {
    parameters: {
      query?: {
        /** @description Filter by report status */
        status?: "pending" | "resolved";
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        per_page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of reports */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            reports?: components["schemas"]["Report"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            per_page?: number;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — administrator access required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  resolveReport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Report resolved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Invalid report ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden — administrator access required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Report not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listComments: {
    parameters: {
      query?: {
        page?: number;
        per_page?: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of comments */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comments?: components["schemas"]["Comment"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            per_page?: number;
          };
        };
      };
      /** @description Invalid torrent ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"];
      };
    };
    responses: {
      /** @description Comment created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comment?: components["schemas"]["Comment"];
          };
        };
      };
      /** @description Invalid request body or empty body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  editComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"];
      };
    };
    responses: {
      /** @description Comment updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comment?: components["schemas"]["Comment"];
          };
        };
      };
      /** @description Invalid request body or empty body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden - not author or admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Comment not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comment deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden - admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Comment not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getRatingStats: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rating statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RatingStats"];
        };
      };
      /** @description Invalid torrent ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  rateTorrent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RateRequest"];
      };
    };
    responses: {
      /** @description Rating submitted, returns updated stats */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RatingStats"];
        };
      };
      /** @description Invalid rating (must be 1-5) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Torrent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
