package handler

// undocumentedRoutes is a debt ledger, not a configuration knob.
//
// backend/api/openapi.yaml is the source of truth for the API, and
// TestEveryRouteIsDocumentedOrKnownUndocumented holds it to the router: every
// route chi actually registers must either be documented there or appear here.
// This map was seeded at the 2026-07 public/full spec split with the 152 routes
// that were undocumented on that day — the spec described 37 of 189.
//
// The rules, in order of how much they matter:
//
//   - Entries may be REMOVED, and only removed. Documenting an endpoint in
//     openapi.yaml and deleting its line here is the whole point; it is how the
//     number above goes down.
//   - Entries MUST NOT be added for a new endpoint. A route added today has its
//     documentation written today, while the person who knows the shape of it is
//     still holding it. Adding a line here instead is choosing to forget.
//   - Nothing may go stale. TestNoStaleUndocumentedEntries fails if an entry
//     names a route that no longer exists, or one that is now documented, so the
//     ledger cannot quietly become a list of endpoints that were deleted years
//     ago.
//
// Keyed by "METHOD /path" with the path exactly as chi reports it, minus any
// trailing slash — chi renders `r.Route("/stats", …)` plus `r.Get("/", …)` as
// `/api/v1/stats/` even though the route answers without the slash.
var undocumentedRoutes = map[string]struct{}{
	"DELETE /api/v1/admin/backups/{name}":                      {},
	"DELETE /api/v1/admin/bans/emails/{id}":                    {},
	"DELETE /api/v1/admin/bans/ips/{id}":                       {},
	"DELETE /api/v1/admin/categories/{id}":                     {},
	"DELETE /api/v1/admin/chat/messages/{id}":                  {},
	"DELETE /api/v1/admin/chat/users/{id}/messages":            {},
	"DELETE /api/v1/admin/chat/users/{id}/mute":                {},
	"DELETE /api/v1/admin/connectors/{id}":                     {},
	"DELETE /api/v1/admin/forum-categories/{id}":               {},
	"DELETE /api/v1/admin/forums/{id}":                         {},
	"DELETE /api/v1/admin/groups/{id}":                         {},
	"DELETE /api/v1/admin/invite-distribution/rules/{groupId}": {},
	"DELETE /api/v1/admin/invites/{id}":                        {},
	"DELETE /api/v1/admin/news/{id}":                           {},
	"DELETE /api/v1/admin/notes/{id}":                          {},
	"DELETE /api/v1/admin/promotion/rules/{groupId}":           {},
	"DELETE /api/v1/admin/restrictions/{id}":                   {},
	"DELETE /api/v1/chat/{id}":                                 {},
	"DELETE /api/v1/messages/drafts/{id}":                      {},
	"DELETE /api/v1/messages/templates/{id}":                   {},
	"DELETE /api/v1/messages/{id}":                             {},
	"GET /api/v1/activity-logs":                                {},
	"GET /api/v1/admin/backups":                                {},
	"GET /api/v1/admin/backups/{name}/download":                {},
	"GET /api/v1/admin/bans/emails":                            {},
	"GET /api/v1/admin/bans/ips":                               {},
	"GET /api/v1/admin/categories":                             {},
	"GET /api/v1/admin/chat/mutes":                             {},
	"GET /api/v1/admin/cheat-flags":                            {},
	"GET /api/v1/admin/connectors":                             {},
	"GET /api/v1/admin/connectors/status":                      {},
	"GET /api/v1/admin/connectors/{id}":                        {},
	"GET /api/v1/admin/connectors/{id}/deliveries":             {},
	"GET /api/v1/admin/dashboard":                              {},
	"GET /api/v1/admin/forum-categories":                       {},
	"GET /api/v1/admin/forums":                                 {},
	"GET /api/v1/admin/groups":                                 {},
	"GET /api/v1/admin/invite-distribution/rules":              {},
	"GET /api/v1/admin/moderation/torrents":                    {},
	"GET /api/v1/admin/news":                                   {},
	"GET /api/v1/admin/promotion/rules":                        {},
	"GET /api/v1/admin/users":                                  {},
	"GET /api/v1/admin/users/{id}":                             {},
	"GET /api/v1/admin/users/{id}/edit-history":                {},
	"GET /api/v1/admin/users/{id}/invites":                     {},
	"GET /api/v1/admin/users/{id}/restrictions":                {},
	"GET /api/v1/admin/warnings":                               {},
	"GET /api/v1/announce-feeds":                               {},
	"GET /api/v1/auth/registration-mode":                       {},
	"GET /api/v1/categories/{id}/metadata-schema":              {},
	"GET /api/v1/chat/history":                                 {},
	"GET /api/v1/chat/mute-status":                             {},
	"GET /api/v1/invites":                                      {},
	"GET /api/v1/invites/{token}":                              {},
	"GET /api/v1/messages/drafts":                              {},
	"GET /api/v1/messages/drafts/{id}":                         {},
	"GET /api/v1/messages/inbox":                               {},
	"GET /api/v1/messages/outbox":                              {},
	"GET /api/v1/messages/templates":                           {},
	"GET /api/v1/messages/templates/{id}":                      {},
	"GET /api/v1/messages/unread-count":                        {},
	"GET /api/v1/messages/{id}":                                {},
	"GET /api/v1/news":                                         {},
	"GET /api/v1/news/{id}":                                    {},
	"GET /api/v1/notifications":                                {},
	"GET /api/v1/notifications/digest-preference":              {},
	"GET /api/v1/notifications/grouped":                        {},
	"GET /api/v1/notifications/preferences":                    {},
	"GET /api/v1/notifications/unread-count":                   {},
	"GET /api/v1/store/items":                                  {},
	"GET /api/v1/torrents/metadata-issues":                     {},
	"GET /api/v1/torrents/{id}/reseed":                         {},
	"GET /api/v1/users":                                        {},
	"GET /api/v1/users/staff":                                  {},
	"GET /api/v1/users/{id}/activity":                          {},
	"GET /api/v1/users/{id}/torrents":                          {},
	"GET /api/v1/users/{id}/warnings":                          {},
	"GET /ws/chat":                                             {},
	"POST /api/v1/admin/backups":                               {},
	"POST /api/v1/admin/bans/emails":                           {},
	"POST /api/v1/admin/bans/ips":                              {},
	"POST /api/v1/admin/categories":                            {},
	"POST /api/v1/admin/chat/users/{id}/mute":                  {},
	"POST /api/v1/admin/connectors":                            {},
	"POST /api/v1/admin/connectors/{id}/test":                  {},
	"POST /api/v1/admin/forum-categories":                      {},
	"POST /api/v1/admin/forums":                                {},
	"POST /api/v1/admin/groups":                                {},
	"POST /api/v1/admin/invite-distribution/run":               {},
	"POST /api/v1/admin/moderation/torrents/{id}/claim":        {},
	"POST /api/v1/admin/moderation/torrents/{id}/reject":       {},
	"POST /api/v1/admin/moderation/torrents/{id}/unclaim":      {},
	"POST /api/v1/admin/news":                                  {},
	"POST /api/v1/admin/promotion/run":                         {},
	"POST /api/v1/admin/users/{id}/ban":                        {},
	"POST /api/v1/admin/users/{id}/notes":                      {},
	"POST /api/v1/admin/warnings":                              {},
	"POST /api/v1/admin/warnings/{id}/lift":                    {},
	"POST /api/v1/auth/confirm-email":                          {},
	"POST /api/v1/auth/resend-confirmation":                    {},
	"POST /api/v1/invites":                                     {},
	"POST /api/v1/messages":                                    {},
	"POST /api/v1/messages/drafts":                             {},
	"POST /api/v1/messages/templates":                          {},
	"POST /api/v1/store/purchase/{itemId}":                     {},
	"POST /api/v1/torrents/{id}/reseed":                        {},
	"PUT /api/v1/admin/categories/reorder":                     {},
	"PUT /api/v1/admin/categories/{id}":                        {},
	"PUT /api/v1/admin/cheat-flags/{id}/dismiss":               {},
	"PUT /api/v1/admin/connectors/{id}":                        {},
	"PUT /api/v1/admin/forum-categories/{id}":                  {},
	"PUT /api/v1/admin/forums/{id}":                            {},
	"PUT /api/v1/admin/groups/{id}":                            {},
	"PUT /api/v1/admin/invite-distribution/rules/{groupId}":    {},
	"PUT /api/v1/admin/news/{id}":                              {},
	"PUT /api/v1/admin/promotion/rules/{groupId}":              {},
	"PUT /api/v1/admin/settings/{key}":                         {},
	"PUT /api/v1/admin/users/{id}":                             {},
	"PUT /api/v1/admin/users/{id}/reset-passkey":               {},
	"PUT /api/v1/admin/users/{id}/reset-password":              {},
	"PUT /api/v1/admin/users/{id}/restrictions":                {},
	"PUT /api/v1/messages/drafts/{id}":                         {},
	"PUT /api/v1/messages/templates/{id}":                      {},
	"PUT /api/v1/notifications/digest-preference":              {},
	"PUT /api/v1/notifications/groups/{key}/read":              {},
	"PUT /api/v1/notifications/preferences":                    {},
	"PUT /api/v1/notifications/read-all":                       {},
	"PUT /api/v1/notifications/{id}/read":                      {},
}
