// Package openapi derives the published, public-facing OpenAPI document from
// the hand-maintained full one.
//
// There is exactly one source of truth — backend/api/openapi.yaml — and every
// operation in it carries an `x-audience` marker saying whether it belongs in
// the published contract. The public document is generated from that marker
// rather than maintained alongside it, because two hand-written specs drift,
// and the way they drift is that an administrative endpoint quietly appears in
// the document handed to third parties.
//
// A path-prefix filter would be the obvious shortcut and it is wrong here: six
// forum moderation endpoints are staff-only but live on ordinary member paths
// (authorization happens in the service layer, not the router), so filtering on
// /api/v1/admin would publish them. The marker is per-operation for that reason.
package openapi

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	// AudienceKey is the OpenAPI extension every operation in the full spec
	// must carry.
	AudienceKey = "x-audience"
	// AudiencePublic marks an operation as part of the published contract.
	AudiencePublic = "public"
	// AudienceInternal marks an operation as excluded from it.
	AudienceInternal = "internal"
)

// publicTitle and publicDescription replace the full spec's own, which say the
// opposite thing: that the document is internal and includes admin endpoints.
const (
	publicTitle       = "TorrentTrader API"
	publicDescription = `The TorrentTrader private tracker API.

The web UI is one client of this API, not a privileged one — anything it can do,
your own client can do too. Authenticate with a bearer token from
POST /api/v1/auth/login, or use your passkey for the tracker and RSS endpoints.

Administrative endpoints are deliberately excluded from this document. They
exist, they are not part of the published contract, and they may change without
notice.`
)

// generatedHeader is emitted verbatim at the top of the public document.
const generatedHeader = `# Code generated by cmd/openapi-public. DO NOT EDIT.
# source: backend/api/openapi.yaml
#
# Regenerate with: task generate:openapi
`

// httpMethods are the keys of a path item that are operations. Everything else
// (parameters, summary, description, servers, $ref) belongs to the path item
// itself and is not audience-scoped.
var httpMethods = map[string]bool{
	"get": true, "put": true, "post": true, "delete": true,
	"options": true, "head": true, "patch": true, "trace": true,
}

// Operation identifies one documented operation and the audience it declares.
type Operation struct {
	// Path is the OpenAPI path template, e.g. "/api/v1/torrents/{id}".
	Path string
	// Method is the upper-case HTTP method, matching what chi.Walk reports.
	Method string
	// Audience is the x-audience value, or "" when the operation declares none.
	Audience string
	// OperationID is the operationId, for error messages that need to name it.
	OperationID string
}

// Key is the "METHOD /path" form used to compare a spec against the router's
// route table.
func (o Operation) Key() string { return o.Method + " " + o.Path }

// Operations lists every operation a spec documents, sorted by method and path
// so callers and their failure messages are deterministic.
func Operations(src []byte) ([]Operation, error) {
	doc, err := parse(src)
	if err != nil {
		return nil, err
	}
	paths, err := requireMap(mapValue(doc.root, "paths"), "paths")
	if err != nil {
		return nil, err
	}

	var ops []Operation
	for i := 0; i+1 < len(paths.Content); i += 2 {
		path := paths.Content[i].Value
		item, err := requireMap(paths.Content[i+1], "paths."+path)
		if err != nil {
			return nil, err
		}
		for j := 0; j+1 < len(item.Content); j += 2 {
			method := item.Content[j].Value
			if !httpMethods[strings.ToLower(method)] {
				continue
			}
			op := item.Content[j+1]
			ops = append(ops, Operation{
				Path:        path,
				Method:      strings.ToUpper(method),
				Audience:    scalarAt(op, AudienceKey),
				OperationID: scalarAt(op, "operationId"),
			})
		}
	}

	sort.Slice(ops, func(a, b int) bool {
		if ops[a].Path != ops[b].Path {
			return ops[a].Path < ops[b].Path
		}
		return ops[a].Method < ops[b].Method
	})
	return ops, nil
}

// Public rewrites the full spec into the published one: internal operations are
// dropped, the x-audience markers are stripped (they are an authoring concern,
// not part of the contract), unreferenced components are pruned, and the title
// and description are replaced with public-facing ones.
//
// The document is edited as a yaml.Node tree rather than round-tripped through
// map[string]any, which would sort every mapping alphabetically and discard
// every comment — turning a one-line spec change into an unreviewable diff, and
// making the byte-for-byte drift check useless.
func Public(src []byte) ([]byte, error) {
	doc, err := parse(src)
	if err != nil {
		return nil, err
	}

	if err := dropInternalOperations(doc.root); err != nil {
		return nil, err
	}
	if err := rewriteInfo(doc.root); err != nil {
		return nil, err
	}
	if err := pruneComponents(doc.root); err != nil {
		return nil, err
	}

	// The full spec's own header explains that it is hand-maintained and
	// internal — the opposite of what the generated file needs to say. yaml.v3
	// hangs a leading comment block off the first key of the root mapping.
	if len(doc.root.Content) > 0 {
		doc.root.Content[0].HeadComment = ""
	}
	doc.node.HeadComment = ""

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc.node); err != nil {
		return nil, fmt.Errorf("encoding public spec: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing encoder: %w", err)
	}
	return buf.Bytes(), nil
}

// --- document plumbing ------------------------------------------------------

type document struct {
	node *yaml.Node // the document node
	root *yaml.Node // the root mapping
}

func parse(src []byte) (*document, error) {
	// A Decoder rather than yaml.Unmarshal, which reads the first document of a
	// stream and silently discards the rest. Quietly generating a public spec
	// from half its input is the kind of failure that only shows up as a
	// missing endpoint months later.
	dec := yaml.NewDecoder(bytes.NewReader(src))
	node := new(yaml.Node)
	if err := dec.Decode(node); err != nil {
		return nil, fmt.Errorf("parsing spec: %w", err)
	}
	if err := dec.Decode(new(yaml.Node)); !errors.Is(err, io.EOF) {
		return nil, errors.New("spec contains more than one YAML document")
	}
	if node.Kind != yaml.DocumentNode || len(node.Content) != 1 {
		return nil, errors.New("spec is not a single YAML document")
	}
	root, err := requireMap(node.Content[0], "root")
	if err != nil {
		return nil, err
	}
	return &document{node: node, root: root}, nil
}

func requireMap(n *yaml.Node, what string) (*yaml.Node, error) {
	if n == nil {
		return nil, fmt.Errorf("spec has no %s", what)
	}
	if n.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("spec %s is not a mapping", what)
	}
	return n, nil
}

// mapValue returns the value node for key, or nil. Safe on a nil or non-mapping
// node so callers can chain lookups on optional sections.
func mapValue(n *yaml.Node, key string) *yaml.Node {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			return n.Content[i+1]
		}
	}
	return nil
}

// scalarAt returns the scalar value at key, or "" when absent or not a scalar.
func scalarAt(n *yaml.Node, key string) string {
	v := mapValue(n, key)
	if v == nil || v.Kind != yaml.ScalarNode {
		return ""
	}
	return v.Value
}

// mapDelete removes key and its value from a mapping.
func mapDelete(n *yaml.Node, key string) {
	if n == nil || n.Kind != yaml.MappingNode {
		return
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			n.Content = append(n.Content[:i], n.Content[i+2:]...)
			return
		}
	}
}

// setScalar replaces the scalar at key, preserving its position. A literal
// block style is used for multi-line values so the generated YAML stays
// readable instead of collapsing into one escaped line.
func setScalar(n *yaml.Node, key, value string) {
	v := mapValue(n, key)
	if v == nil {
		return
	}
	v.Kind = yaml.ScalarNode
	v.Tag = "!!str"
	v.Value = value
	v.Content = nil
	v.Style = 0
	if strings.Contains(value, "\n") {
		v.Style = yaml.LiteralStyle
	}
}

// --- the transformations ----------------------------------------------------

// dropInternalOperations removes every x-audience: internal operation, then
// every path item those emptied out, and strips the markers from the rest.
func dropInternalOperations(root *yaml.Node) error {
	paths, err := requireMap(mapValue(root, "paths"), "paths")
	if err != nil {
		return err
	}

	kept := make([]*yaml.Node, 0, len(paths.Content))
	for i := 0; i+1 < len(paths.Content); i += 2 {
		key, item := paths.Content[i], paths.Content[i+1]
		itemMap, err := requireMap(item, "paths."+key.Value)
		if err != nil {
			return err
		}

		keptOps := make([]*yaml.Node, 0, len(itemMap.Content))
		var operations int
		for j := 0; j+1 < len(itemMap.Content); j += 2 {
			field, value := itemMap.Content[j], itemMap.Content[j+1]
			if !httpMethods[strings.ToLower(field.Value)] {
				keptOps = append(keptOps, field, value)
				continue
			}
			if scalarAt(value, AudienceKey) == AudienceInternal {
				continue
			}
			mapDelete(value, AudienceKey)
			operations++
			keptOps = append(keptOps, field, value)
		}
		itemMap.Content = keptOps

		// A path item with no operations left describes nothing. Keeping it
		// would advertise the path's existence, which is exactly what dropping
		// the operations was for.
		if operations == 0 {
			continue
		}
		kept = append(kept, key, item)
	}
	paths.Content = kept
	return nil
}

func rewriteInfo(root *yaml.Node) error {
	info, err := requireMap(mapValue(root, "info"), "info")
	if err != nil {
		return err
	}
	if mapValue(info, "title") == nil {
		return errors.New("spec info has no title")
	}
	if mapValue(info, "description") == nil {
		return errors.New("spec info has no description")
	}
	setScalar(info, "title", publicTitle)
	setScalar(info, "description", publicDescription)
	return nil
}

// pruneComponents drops component schemas nothing reaches any more and security
// schemes nothing declares any more.
//
// Without this the public document keeps every admin-only request and response
// shape, which is a more detailed description of the endpoints just removed than
// the endpoints themselves were.
func pruneComponents(root *yaml.Node) error {
	components := mapValue(root, "components")
	if components == nil {
		return nil
	}
	if _, err := requireMap(components, "components"); err != nil {
		return err
	}

	if schemas := mapValue(components, "schemas"); schemas != nil {
		if _, err := requireMap(schemas, "components.schemas"); err != nil {
			return err
		}
		keepSchemas(root, components, schemas)
	}
	if schemes := mapValue(components, "securitySchemes"); schemes != nil {
		if _, err := requireMap(schemes, "components.securitySchemes"); err != nil {
			return err
		}
		keepSecuritySchemes(root, schemes)
	}

	// An emptied-out section is noise; an emptied-out components block is
	// worse, because `components: {}` reads as "there are none" rather than
	// "there is nothing left to say".
	for _, section := range []string{"schemas", "securitySchemes"} {
		if s := mapValue(components, section); s != nil && len(s.Content) == 0 {
			mapDelete(components, section)
		}
	}
	if len(components.Content) == 0 {
		mapDelete(root, "components")
	}
	return nil
}

// keepSchemas removes every schema unreachable from the surviving document.
//
// Reachability is transitive: a schema referenced only by another schema that
// itself survives has to stay, or the published document would $ref into a
// void.
func keepSchemas(root, components, schemas *yaml.Node) {
	// Seed from everything outside components.schemas — the surviving paths,
	// root-level security, and the component sections that are not pruned (a
	// shared response body may reference a schema too).
	var frontier []string
	for i := 0; i+1 < len(root.Content); i += 2 {
		if root.Content[i].Value == "components" {
			continue
		}
		frontier = append(frontier, schemaRefs(root.Content[i+1])...)
	}
	for i := 0; i+1 < len(components.Content); i += 2 {
		if components.Content[i].Value == "schemas" {
			continue
		}
		frontier = append(frontier, schemaRefs(components.Content[i+1])...)
	}

	reachable := make(map[string]bool)
	for len(frontier) > 0 {
		name := frontier[len(frontier)-1]
		frontier = frontier[:len(frontier)-1]
		if reachable[name] {
			continue
		}
		reachable[name] = true
		frontier = append(frontier, schemaRefs(mapValue(schemas, name))...)
	}

	kept := make([]*yaml.Node, 0, len(schemas.Content))
	for i := 0; i+1 < len(schemas.Content); i += 2 {
		if reachable[schemas.Content[i].Value] {
			kept = append(kept, schemas.Content[i], schemas.Content[i+1])
		}
	}
	schemas.Content = kept
}

const schemaRefPrefix = "#/components/schemas/"

// schemaRefs collects every '#/components/schemas/X' reference under a node.
func schemaRefs(n *yaml.Node) []string {
	if n == nil {
		return nil
	}
	var refs []string
	if n.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(n.Content); i += 2 {
			if n.Content[i].Value == "$ref" && n.Content[i+1].Kind == yaml.ScalarNode {
				if name, ok := strings.CutPrefix(n.Content[i+1].Value, schemaRefPrefix); ok {
					refs = append(refs, name)
				}
			}
		}
	}
	for _, child := range n.Content {
		refs = append(refs, schemaRefs(child)...)
	}
	return refs
}

// keepSecuritySchemes removes schemes no surviving operation and no root-level
// requirement names. Security requirements refer to schemes by key, not by
// $ref, so this cannot ride on the schema walk.
func keepSecuritySchemes(root, schemes *yaml.Node) {
	used := make(map[string]bool)
	for i := 0; i+1 < len(root.Content); i += 2 {
		key, value := root.Content[i], root.Content[i+1]
		if key.Value == "components" {
			continue
		}
		// The root-level requirement is reached through the key rather than
		// found nested inside the value, so it needs handling of its own —
		// missing it would prune a scheme every operation inherits.
		if key.Value == "security" {
			for _, name := range requirementNames(value) {
				used[name] = true
			}
		}
		for _, name := range securitySchemeNames(value) {
			used[name] = true
		}
	}

	kept := make([]*yaml.Node, 0, len(schemes.Content))
	for i := 0; i+1 < len(schemes.Content); i += 2 {
		if used[schemes.Content[i].Value] {
			kept = append(kept, schemes.Content[i], schemes.Content[i+1])
		}
	}
	schemes.Content = kept
}

// securitySchemeNames collects the keys named by every `security:` requirement
// list under a node.
func securitySchemeNames(n *yaml.Node) []string {
	if n == nil {
		return nil
	}
	var names []string
	if n.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(n.Content); i += 2 {
			if n.Content[i].Value == "security" {
				names = append(names, requirementNames(n.Content[i+1])...)
			}
		}
	}
	for _, child := range n.Content {
		names = append(names, securitySchemeNames(child)...)
	}
	return names
}

// requirementNames collects the scheme keys named by a `security:` requirement
// list, given the list itself rather than the mapping that holds it. The
// root-level requirement is reached that way, so it cannot use the walk above.
func requirementNames(list *yaml.Node) []string {
	if list == nil || list.Kind != yaml.SequenceNode {
		return nil
	}
	var names []string
	for _, requirement := range list.Content {
		if requirement.Kind != yaml.MappingNode {
			continue
		}
		for i := 0; i+1 < len(requirement.Content); i += 2 {
			names = append(names, requirement.Content[i].Value)
		}
	}
	return names
}
